services:
  airquality:
    image: airquality
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul-dev
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - consul-importer
      - rabbitmq-dev
    networks:
      - micro_airquality

  frontend:
    image: frontend
    ports:
      - '3000:80'
    networks:
      - micro_airquality

  airqualitynotification:
    image: airqualitynotification
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul-dev
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - consul-importer
      - rabbitmq-dev
    networks:
      - micro_airquality

  airqualityhistory:
    image: airqualityhistory
    ports:
      - '8087:8087'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul-dev
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - consul-importer
      - rabbitmq-dev
    networks:
      - micro_airquality

  gateway:
    image: gateway
    ports:
      - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul-dev
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - micro_airquality

  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '15672:15672'
    networks:
      - micro_airquality

  consul-dev:
    image: hashicorp/consul:1.19.2
    container_name: consul
    ports:
      - '8500:8500'
    command: 'agent -dev -node=AirQuality -client=0.0.0.0 -log-level=INFO'
    networks:
      - micro_airquality

  consul-importer:
    image: consul-importer
    depends_on:
      - consul-dev
    networks:
      - micro_airquality

networks:
  micro_airquality:
    driver: bridge